### ISSUE TITLE
Production ready

### ISSUE THREAD

**Issue by martinbertinat** [siarheipashkevich/loyverse-sdk#1]
Hi! thanks for your work.

We are thinking about building a product and we want to know if you think your library is production ready?

Are you using it for a product of your own?

We are building a website in which customers can order directly to shops.

Thanks!

**Comment by siarheipashkevich** [comment]
Hi @martinbertinat.

I don't use this package on production yet.
I'll support this package if you will use it on production and find any issues.

Please pay attention to minimal version of the PHP is ^7.4
https://github.com/siarheipashkevich/loyverse-sdk/blob/master/composer.json#L21

**Comment by martinbertinat** [comment]
OK no problem!

Can I know what motivates you to make this package?

Thank you

**Comment by siarheipashkevich** [comment]
I'm going to use this package for future development third-party packages, plugins etc.
