### ISSUE TITLE
createReceipt() is missing

### ISSUE THREAD

**Issue by kevin700523** [siarheipashkevich/loyverse-sdk#2]
Hi! thanks for your work.

There's something Error, it shows:
Call to undefined method Pashkevich\Loyverse\Loyverse::createReceipt()

Seems createReceipt() function is missing.

**Comment by siarheipashkevich** [comment]
@kevin700523 thank you.
Do you have an ability to open PR?

**Comment by siarheipashkevich** [comment]
Closed https://github.com/siarheipashkevich/loyverse-sdk/commit/3adbd7146697a9d8de01500267e61c84acc646c2
