### ISSUE TITLE
Ability to access tickets.

### ISSUE THREAD

**Issue by andyg2** [siarheipashkevich/loyverse-sdk#3]
Lovely sdk you have here.
I can't find how to access current loyverse tickets and checking the loyverse API documentation I can't find it there either.
I imagine you've run across the same inexplicable omission but did you find any way of accessing this data?

**Comment by siarheipashkevich** [comment]
Hi @andyg2 
Please read the doc https://github.com/siarheipashkevich/loyverse-sdk#loyverse-sdk

**Comment by andyg2** [comment]
> Hi @andyg2 Please read the doc https://github.com/siarheipashkevich/loyverse-sdk#loyverse-sdk

Thanks for the link however there's no mention of tickets there, only receipts. I guess it's not implemented.

**Comment by siarheipashkevich** [comment]
Got it. But I can't see this entity in the official doc of the Loyverse.
https://developer.loyverse.com/docs/

**Comment by andyg2** [comment]
Yeah, it's a startling omission for a POS, especially after weeks of (wasted) work. Thanks for your help though and thanks for your SDK too :)
