### ISSUE TITLE
Error returns when request customer from /customers/{customer_id}

### ISSUE THREAD

**Issue by brandonccy** [siarheipashkevich/loyverse-sdk#4]
Found a API bug on Resources/Customer when do customer query with customer ID.

 PHP Fatal error:  Uncaught TypeError: Typed property Pashkevich\\Loyverse\\Resources\\Customer::$name must be string, null used in /var/www/html/vendor/pashkevich/loyverse-sdk/src/Resources/Resource.php:52

Line 24: public string $name;

Changed to 

Line 24: public ?string $name;

to fix.

**Comment by siarheipashkevich** [comment]
Hi @brandonccy thanks for issue.

Which request are you doing? Could you please provide more info?

**Comment by brandonccy** [comment]
Line 24 of 

https://github.com/siarheipashkevich/loyverse-sdk/blob/f42a76497fa51ddebe73970ffba890214b0587d5/src/Resources/Customer.php#L24

Here, it fixed when I changed to the following:
Changed to

public ?string $name;

**Comment by siarheipashkevich** [comment]
I got it. But by the spec `name` can't be null for customer because this field is required.

![image](https://user-images.githubusercontent.com/7753600/173558181-6d993228-844b-4e1f-a19f-54c8594d2e72.png)

Can you show data of your customer?

**Comment by brandonccy** [comment]
The request is on (GET) query . So the "name" field is not required. But it is when doing (POST) create or update.
I noticed that there are no issue on ITEMS & CATEGORY.

**Comment by siarheipashkevich** [comment]
@brandonccy I want to understand why your customer does not have `name` and how you added this customer without `name`?

The sdk related to loyverse api where `name` field for customer is required.

**Comment by brandonccy** [comment]
Sure, 
Below is how I get customer data just like the rest of your other methods

Here how I successfully get Item details
```
// $item_id = "d50b40e2-76b5-487f-b9f1-be60d48cd459";
$getItemData =  = json_encode($loyverse->item($item_id));
```

When I tried to get customer details, it return type error.
```
// $customer_id= "9553152a-9d9e-8844-f6a3-2ab7d934516c";
$getCustomerData = json_encode($loyverse->customer($customer_id));
```

PHP Fatal error: Uncaught TypeError: Typed property Pashkevich\Loyverse\Resources\Customer::$name must be string, null used in /var/www/html/vendor/pashkevich/loyverse-sdk/src/Resources/Resource.php:52

**Comment by siarheipashkevich** [comment]
Could you submit PR please?

**Comment by brandonccy** [comment]
> Could you submit PR please?

Hi. Do you meant pull request?

**Comment by siarheipashkevich** [comment]
@brandonccy yes

**Comment by siarheipashkevich** [comment]
> @brandonccy I want to understand why your customer does not have `name` and how you added this customer without `name`?
> 
> The sdk related to loyverse api where `name` field for customer is required.

Closed because there was no answer to this question. Please re-open or create a new issue if needed.
