### ISSUE TITLE
Class "App\Http\Controllers\Pashkevich\Loyverse\Loyverse" not found

### ISSUE THREAD

**Issue by alican22** [siarheipashkevich/loyverse-sdk#5]
How to Include class in controller?

I m getting error.

Class "App\Http\Controllers\Pashkevich\Loyverse\Loyverse" not found

**Comment by siarheipashkevich** [comment]
@alican22 `Pashkevich\Loyverse\Loyverse` this is valid path for class. Could you please provide more information how you are using package?

**Comment by alican22** [comment]
It doesn't allow me to use this class. Please see my example code below.

`<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use Pashkevich\Loyverse\Loyverse;

class LoyverseController extends Controller
{
    public function index() {

        $loyverse = new Pashkevich\Loyverse\Loyverse('rZEsMag57MW5MvB1apXF-mLpujjJUJ-lv_m-_luYZDScg--LHmh_dw==');
        $categories = $loyverse->categories();
        dd($categories);

        return view('loyverse');
    }
}`

**Comment by siarheipashkevich** [comment]
Please add `\` before `Pashkevich..`.

`$loyverse = new \Pashkevich\Loyverse\Loyverse('rZEsMag57MW5MvB1apXF-mLpujjJUJ-lv_m-_luYZDScg--LHmh_dw==');`

or you already imported class to the namespace and you can write just:
`$loyverse = new Loyverse('rZEsMag57MW5MvB1apXF-mLpujjJUJ-lv_m-_luYZDScg--LHmh_dw==');`

**Comment by alican22** [comment]
> Please add `\` before `Pashkevich..`.
> 
> `$loyverse = new \Pashkevich\Loyverse\Loyverse('rZEsMag57MW5MvB1apXF-mLpujjJUJ-lv_m-_luYZDScg--LHmh_dw==');`
> 
> or you already imported class to the namespace and you can write just: `$loyverse = new Loyverse('rZEsMag57MW5MvB1apXF-mLpujjJUJ-lv_m-_luYZDScg--LHmh_dw==');`

Thank you so much

**Comment by siarheipashkevich** [comment]
You are welcome, thanks for trying my package.

Let me know if there are any problems.
