### ISSUE TITLE
Issue with Class "App\Http\Controllers\Pashkevich\Loyverse\Loyverse" Not Found

### ISSUE THREAD

**Issue by ourada84** [siarheipashkevich/loyverse-sdk#6]
Hello 

I hope this message finds you well. I am currently facing an issue with the usage of your Loyverse SDK in my Laravel project. I have followed the installation steps mentioned in the documentation, but I am encountering the error "Class "App\Http\Controllers\Pashkevich\Loyverse\Loyverse" not found."

Here are the details of my environment:

PHP Version: 8.2.13
Laravel Version: 9.52.16
Composer Packages:
pashkevich/loyverse-sdk: ^1.0
Steps I have taken to resolve the issue:

Ensured that the composer autoload section in composer.json includes the correct PSR-4 autoloading for the Loyverse SDK.

composer.json

```
"autoload": {
    "psr-4": {
        "Pashkevich\\Loyverse\\": "vendor/pashkevich/loyverse-sdk/src"
    }
}
```
Executed the composer dump-autoload command to regenerate the autoload files.

Verified that the Loyverse SDK files exist in the vendor/pashkevich/loyverse-sdk/src directory.

Checked the namespace and class name in the Loyverse SDK file (Loyverse.php) and ensured it matches the one I am using in my controller.

Attempted to reinstall the Loyverse SDK by running composer remove pashkevich/loyverse-sdk followed by composer require pashkevich/loyverse-sdk.

Restarted the Apache server.

Cleared Laravel cache using php artisan cache:clear.

Despite these efforts, the issue persists, and I am unable to instantiate the Loyverse class in my controller.

Here is a snippet of my controller code:

```

use Pashkevich\Loyverse\Loyverse;

class LoyverseController extends Controller
{
    public function importShifts()
    {
        $Loy = new Pashkevich\Loyverse\Loyverse('xxxxx token xxxxxxx');
        $shifts = $Loy->shifts(['limit' => 10]);
        dd($shifts);
    }
}
```
I would sincerely appreciate any guidance or assistance you can provide in resolving this issue. I have reached a point of frustration and any help would be immensely valuable.

Thank you for your time and consideration.

Best regards,
Lukas

**Comment by siarheipashkevich** [comment]
Hello

1) you do not need to override any paths in composer file
2) in your controller you already included namespace of package, then you should use Loyverse without any namespace

```
use Pashkevich\Loyverse\Loyverse;

// in code
$loyverse = new Loyverse(...
```

Let me know if you have any issues.

**Comment by siarheipashkevich** [comment]
Please take a look at the same issue https://github.com/siarheipashkevich/loyverse-sdk/issues/5

**Comment by siarheipashkevich** [comment]
@ourada84 I'm going to close this issue, because it's your configuration problem. Please reopen if you are not agree.
